# Returns absolute stats in m^3 for a given axis aligned bounding box.

BoundingBox bbox
---
float64 occupied
float64 free
float64 unknown
float64 total
float64 cell_volume
CellId bbox_min
CellId bbox_max
