# Request:
# Only roi and sample_size are required. All other fields are either optional or default to legal values.
# - roi: List of  regions of interest
# - sample_size: The requested amount of samples (response may contain less).
# - timeout: Optional: Timeout after which sampling is aborted.
# - ray_skip: Probability that a ray cast will be skipped (speeds up information gain estimation).
# - observation_point: Optional: If set, sampling is restricted poses at the given point.
# - lockt_height: Only relevant when observation_point is set: Whether camera height should
#                 be locked (true) or free  (false) for sampling.
# - omit_cvm: If set to true, no conditional visibility maps are included in the response (reduces msg size). 
# - keep_blind_poses If set to true, allows view poses in the response that see no cells
# - objects: List of bounding boxes for moveable objects in the scene.
#
# Response:
# - roi_cell_counts: Number of cells in the requested regions of interest
# - camera_poses: A List of camera poses in the world coordinate frame from which the ROI can be observed
# - target_points: A point in the center of the camera viewport at the corresponding camera pose.
#                  Can be used as target for point_head.
# - information_gain: A list of expected information gain for each camera pose.
#                     Information gain is measured as revealed space [m^3]
# - cvm: A list containing the conditional visibility map for each camera pose.
#        Always empty if omit_cvm is set to true.

BoundingBox[] roi
int32 sample_size
duration timeout
float32 ray_skip
geometry_msgs/PointStamped observation_position
bool lock_height
bool omit_cvm
bool keep_blind_poses
BoundingBox[] objects
---
uint32[] roi_cell_counts
geometry_msgs/Pose[] camera_poses
geometry_msgs/Point[] target_points
float32[] information_gains
ConditionalVisibilityMap[] cvms
ObjectSet[] object_sets
